FootballManager/urls.py
from django.urls import path
from django.contrib import admin
from .views.table import TableView
from .views.teams import TeamsView, Add_Team, Info_Team, Edit_Team, Delete_Team
from .views.footballers import FootballersView, Add_Footballer, Info_Footballer, Edit_Footballer, Delete_Footballer
from .views.matches import  MatchesView, Add_Match, Add_Match_Result, Info_Match, Edit_Match, Delete_Match
from .views.queues import QueueView, Add_Queue, Info_Queue, Edit_Queue, Delete_Queue
from .views.statistics import StatisticView
from .views.auth import custom_login, custom_logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', TableView.as_view(), name='Table'),
    path('table/', TableView.as_view(), name='Table'),
    path('teams/', TeamsView.as_view(), name='Teams'),
    path('teams/add/', Add_Team, name='Add Team'),
    path('teams/info/<int:team_id>/', Info_Team, name='Info team'),
    path('teams/edit/<int:team_id>/', Edit_Team, name='Edit team'),
    path('teams/delete/<int:team_id>/', Delete_Team, name='Delete team'),
    path('footballers/', FootballersView.as_view(), name='Footballers'),
    path('footballers/add/', Add_Footballer, name='Add Footballer'),
    path('footballers/info/<int:footballer_id>/', Info_Footballer, name='Info footballer'),
    path('footballers/edit/<int:footballer_id>/', Edit_Footballer, name='Edit footballer'),
    path('footballers/delete/<int:footballer_id>/', Delete_Footballer, name='Delete footballer'),
    path('matches/', MatchesView.as_view(), name='Matches'),
    path('matches/add/', Add_Match, name='Add Match'),
    path('matches/info/<int:match_id>/', Info_Match, name='Info match'),
    path('matches/edit/<int:match_id>/', Edit_Match, name='Edit match'),
    path('matches/result/<int:match_id>/', Add_Match_Result, name='Add match result'),
    path('matches/delete/<int:match_id>/', Delete_Match, name='Delete match'),
    path('queues/', QueueView.as_view(), name='Queues'),
    path('queues/add/', Add_Queue, name='Add queue'),
    path('queues/info/<int:queue_id>/', Info_Queue, name='Info queue'),
    path('queues/edit/<int:queue_id>/', Edit_Queue, name='Edit queue'),
    path('queues/delete/<int:queue_id>/', Delete_Queue, name='Delete queue'),
    path('statistics/', StatisticView.as_view(), name='Statistics'),
    path('login/', custom_login, name='Login'),
    path('logout/', custom_logout, name='Logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FootballManager/models.py
from django.db import models, transaction
from django.db.models import F


class Team(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    trainer = models.CharField(max_length=60, blank=True, null=True)
    wins = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    goals_scored = models.IntegerField(default=0)
    goals_lost = models.IntegerField(default=0)
    logo = models.ImageField(upload_to='team_logos/', blank=True, null=True)
    description = models.TextField(blank=True)

    def matches_played(self):
        return Match.objects.filter(models.Q(host_team=self) | models.Q(guest_team=self)).count()

    def __str__(self):
        return f"{self.name}"


class Footballer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='team', null=True)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Event(models.Model):
    class EventType(models.TextChoices):
        GOAL = 'GOAL', 'Gol'
        ASSIST = 'ASSIST', 'Asysta'
        YELLOW_CARD = 'YELLOW CARD', 'Żółta kartka'
        RED_CARD = 'RED CARD', 'Czerwona kartka'
        OWN_GOAL = 'OWN GOAL', 'Gol samobójczy'

    id = models.AutoField(primary_key=True)
    minute = models.IntegerField(blank=False, default=0)
    footballer = models.ForeignKey('Footballer', on_delete=models.CASCADE, null=True)
    match = models.ForeignKey('Match', on_delete=models.CASCADE, null=True, related_name='events')
    event_type = models.CharField(max_length=20, choices=EventType.choices, default=EventType.GOAL)

    def update_statistics(self, original_event=None):
        # Rollback stats if the event was changed
        if original_event:
            if original_event.event_type == self.EventType.GOAL:
                Statistic.objects.filter(footballer=original_event.footballer).update(goals_scored=F('goals_scored') - 1)
            elif original_event.event_type == self.EventType.ASSIST:
                Statistic.objects.filter(footballer=original_event.footballer).update(assists=F('assists') - 1)
            elif original_event.event_type == self.EventType.YELLOW_CARD:
                Statistic.objects.filter(footballer=original_event.footballer).update(yellow_cards=F('yellow_cards') - 1)
            elif original_event.event_type == self.EventType.RED_CARD:
                Statistic.objects.filter(footballer=original_event.footballer).update(red_cards=F('red_cards') - 1)
            elif original_event.event_type == self.EventType.OWN_GOAL:
                Statistic.objects.filter(footballer=original_event.footballer).update(own_goals=F('own_goals') - 1)

        # Update stats for the new event
        if self.event_type == self.EventType.GOAL:
            Statistic.objects.filter(footballer=self.footballer).update(goals_scored=F('goals_scored') + 1)
        elif self.event_type == self.EventType.ASSIST:
            Statistic.objects.filter(footballer=self.footballer).update(assists=F('assists') + 1)
        elif self.event_type == self.EventType.YELLOW_CARD:
            Statistic.objects.filter(footballer=self.footballer).update(yellow_cards=F('yellow_cards') + 1)
        elif self.event_type == self.EventType.RED_CARD:
            Statistic.objects.filter(footballer=self.footballer).update(red_cards=F('red_cards') + 1)
        elif self.event_type == self.EventType.OWN_GOAL:
            Statistic.objects.filter(footballer=self.footballer).update(own_goals=F('own_goals') + 1)

    def save(self, *args, **kwargs):
        with transaction.atomic():
            # Check if this is an update
            if self.pk:
                original_event = Event.objects.get(pk=self.pk)
                if original_event.footballer != self.footballer or original_event.event_type != self.event_type:
                    self.update_statistics(original_event=original_event)
            else:
                # If it's a new event, just update the statistics
                self.update_statistics()

            super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.event_type} {self.minute}"
    
    


class Queue(models.Model):
    id = models.AutoField(primary_key=True)
    number = models.IntegerField(default=0)

    def __str__(self):
        return f"Kolejka {self.number}"

class Match(models.Model):
    id = models.AutoField(primary_key=True)
    host_team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='host_team', null=True)
    guest_team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='guest_team', null=True)
    date = models.DateTimeField(null=True)
    host_goals = models.IntegerField(null=True)
    guest_goals = models.IntegerField(null=True)
    queue = models.ForeignKey(Queue, on_delete=models.CASCADE, related_name='matches', null=True)

    def __str__(self):
        return f"{self.host_team} {self.host_goals} - {self.guest_goals} {self.guest_team}"


class Statistic(models.Model):
    id = models.AutoField(primary_key=True)
    footballer = models.ForeignKey('Footballer', on_delete=models.CASCADE)
    matches_played = models.IntegerField(default=0)
    goals_scored = models.IntegerField(default=0)
    assists = models.IntegerField(default=0)
    yellow_cards = models.IntegerField(default=0)
    red_cards = models.IntegerField(default=0)
    own_goals = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.footballer.name}"

FootballManager/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import F, Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db import models, transaction

from .models import Footballer, Team, Match, Queue, Statistic
from .forms import FootballerForm, TeamForm, MatchForm, QueueForm, EventForm, MatchResultForm


class TableView(generic.ListView):
    template_name = "FootballManager/table.html"
    context_object_name = "teams"

    def get_queryset(self):
        teams = Team.objects.annotate(
            host_matches_count=models.Count('host_team', filter=Q(host_team__isnull=False)),
            guest_matches_count=models.Count('guest_team', filter=Q(guest_team__isnull=False)),
        )
        for team in teams:
            team.matches_count = team.host_matches_count + team.guest_matches_count
            team.points = team.wins * 3 + team.draws
            team.goals_balance = team.goals_scored - team.goals_lost
        return teams


class TeamsView(generic.ListView):
    template_name = "FootballManager/teams.html"
    context_object_name = "teams"

    def get_queryset(self):
        return Team.objects.order_by("-name")


class FootballersView(generic.ListView):
    template_name = "FootballManager/footballers.html"
    context_object_name = "footballers"

    def get_queryset(self):
        return Footballer.objects.order_by("-name")

    
class MatchesView(generic.ListView):
    template_name = "FootballManager/matches.html"
    context_object_name = "matches"

    def get_queryset(self):
        return Match.objects.order_by("-host_team")


class QueueView(generic.ListView):
    template_name = "FootballManager/queue.html"
    context_object_name = "queues"

    def get_queryset(self):
        return Queue.objects.order_by("id")


class StatisticView(generic.ListView):
    template_name = "FootballManager/statistics.html"
    context_object_name = "statistics"

    def get_queryset(self):
        return Statistic.objects.select_related('footballer').order_by("-goals_scored")
    

def Add_Footballer(request):
    form = FootballerForm()

    if request.method == 'POST':
        form = FootballerForm(request.POST)
        if form.is_valid():
            footballer = form.save()
            Statistic.objects.create(footballer=footballer)
            return redirect('Footballers')

    template_name = "FootballManager/add_footballer.html"
    context = {'form': form}
    return render(request, template_name, context)


def Add_Team(request):
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Teams')
    else:
        form = TeamForm()

    context = {'form': form}
    return render(request, 'FootballManager/add_team.html', context)


def update_team_statistics(team, goals_scored, goals_lost, is_winner, is_draw):
    if is_winner:
        team.wins += 1
    elif is_draw:
        team.draws += 1
    else:
        team.losses += 1

    team.goals_scored += goals_scored
    team.goals_lost += goals_lost
    team.save()

@transaction.atomic
def update_team_stats_for_match(host_team, guest_team, host_goals, guest_goals):
    if host_goals > guest_goals:
        update_team_statistics(host_team, host_goals, guest_goals, is_winner=True, is_draw=False)
        update_team_statistics(guest_team, guest_goals, host_goals, is_winner=False, is_draw=False)
    elif host_goals < guest_goals:
        update_team_statistics(host_team, host_goals, guest_goals, is_winner=False, is_draw=False)
        update_team_statistics(guest_team, guest_goals, host_goals, is_winner=True, is_draw=False)
    else:
        update_team_statistics(host_team, host_goals, guest_goals, is_winner=False, is_draw=True)
        update_team_statistics(guest_team, guest_goals, host_goals, is_winner=False, is_draw=True)


def Add_Match(request):
    if request.method == 'POST':
        match_form = MatchForm(request.POST)
        if match_form.is_valid():
            match_form.save()
            

            return redirect('Matches')
    else:
        match_form = MatchForm()

    context = {'match_form': match_form}
    return render(request, 'FootballManager/add_match.html', context)

def Add_Match_Result(request, match_id):
    match = get_object_or_404(Match, pk=match_id)
    if request.method == 'POST':
        matchresult_form = MatchResultForm(request.POST)
        if matchresult_form.is_valid():
            matchresult = matchresult_form.save()
            update_team_stats_for_match(
                            match.host_team,
                            match.guest_team,
                            matchresult.host_goals,
                            matchresult.guest_goals
                        )
            return redirect('Matches')
    else:
        matchresult_form = MatchResultForm()

    context = {'match': match, 'matchresult_form': matchresult_form}
    return render(request, 'FootballManager/add_match_result.html', context)


def Add_to_queue(request, queue_id):
    queue = get_object_or_404(Queue, pk=queue_id)
    matches = Match.objects.all()

    if request.method == 'POST':
        match_ids = request.POST.getlist('matches[]')
        selected_matches = Match.objects.filter(pk__in=match_ids)

        for match in queue.matches.all():
            if match not in selected_matches:
                queue.matches.remove(match)

        for match in selected_matches:
            queue.matches.add(match)

        return redirect('Queue')

    context = {'matches': matches, 'queue': queue}
    return render(request, 'FootballManager/add_to_queue.html', context)



@login_required
def custom_logout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("Table")


def custom_login(request):
    if request.user.is_authenticated:
        return redirect('Table')

    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                messages.success(request, f"Hello <b>{user.username}</b>! You have been logged in")
                return redirect('Table')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    form = AuthenticationForm()

    return render(
        request=request,
        template_name="users/login.html",
        context={'form': form}
    )

FootballManager/views/footballers.py
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from FootballManager.models import Footballer, Statistic, Team
from FootballManager.forms import FootballerForm

class FootballersView(generic.ListView):
    template_name = "FootballManager/footballers/footballers.html"
    context_object_name = "footballers"

    def get_queryset(self):
        return Footballer.objects.order_by("-name")

def Add_Footballer(request):
    form = FootballerForm()
    if request.method == 'POST':
        form = FootballerForm(request.POST)
        if form.is_valid():
            footballer = form.save()
            Statistic.objects.create(footballer=footballer)
            return redirect('Footballers')

    template_name = "FootballManager/footballers/add_footballer.html"
    context = {'form': form}
    return render(request, template_name, context)

def Info_Footballer(request, footballer_id):
    footballer = get_object_or_404(Footballer, pk=footballer_id)
    context = {'footballer': footballer}
    return render(request, 'FootballManager/footballers/info_footballer.html', context)

def Edit_Footballer(request, footballer_id):
    footballer = get_object_or_404(Footballer, pk=footballer_id)

    if request.method == 'POST':
        form = FootballerForm(request.POST, instance=footballer)
        if form.is_valid():
            form.save()
            return redirect('Footballers')
    else:
        form = FootballerForm(instance=footballer)

    teams = Team.objects.all()

    context = {'form': form, 'footballer': footballer, 'teams': teams}
    return render(request, 'FootballManager/footballers/edit_footballer.html', context)



def Delete_Footballer(request, footballer_id):
    footballer = get_object_or_404(Footballer, pk=footballer_id)
    footballer.delete()
    return redirect('Footballers')

FootballManager/views/statistics.py
from django.views import generic
from FootballManager.models import Statistic

class StatisticView(generic.ListView):
    template_name = "FootballManager/statistics.html"
    context_object_name = "statistics"

    def get_queryset(self):
        return Statistic.objects.select_related('footballer').order_by("-goals_scored")

FootballManager/templates/FootballManager/matches/add_match.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="columns is-centered">
        <div class="column is-half">
            <h1 class="title has-text-centered">Dodaj mecz</h1>
            <div class="box">
                <form method="post" class="form">
                    {% csrf_token %}
                    {% if match_form.non_field_errors %}
                        <div class="notification is-danger">
                            {{ match_form.non_field_errors }}
                        </div>
                    {% endif %}

                    <div class="field">
                        <label class="label">Data meczu</label>
                        <div class="control">
                            <input type="datetime-local" class="input" name="date">
                            {% if match_form.date.errors %}
                                <p class="help custom-error">Data nie może byc pusta</p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Gospodarze</label>
                        <div class="control">
                            <div class="select">
                                {{ match_form.host_team }}
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Goście</label>
                        <div class="control">
                            <div class="select">
                                {{ match_form.guest_team }}
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Kolejka</label>
                        <div class="control">
                            <div class="select">
                                {{ match_form.queue }}
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control has-text-centered">
                            <button class="button is-primary" type="submit">Dodaj</button>
                            <a class="button is-light" href="{% url 'Matches' %}">Anuluj</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .custom-error {
        color: red;
        font-size: 14px;
    }
</style>
{% endblock %}

FootballManager/templates/FootballManager/matches/edit_match.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="columns is-centered">
        <div class="column is-half">
            <h1 class="title has-text-centered">Edytuj mecz</h1>
            <div class="box">
                <form method="post" class="form">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="notification is-danger">
                            {% for error in form.non_field_errors %}
                                <p class="help custom-error">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <div class="columns is-multiline is-mobile">
                        <div class="column is-half">
                            <label class="label">Data meczu</label>
                            <div class="control">
                                <input class="input" type="datetime-local" name="date"
                                    value="{% if form.instance.date %}{{ form.instance.date|date:'Y-m-d\TH:i' }}{% else %}{{ form.date.value|date:'Y-m-d\TH:i' }}{% endif %}" placeholder="Wprowadź datę meczu">
                            </div>
                            {% if form.date.errors %}
                                <p class="help error">Data nie może być pusta.</p>
                            {% endif %}
                        </div>
                        <div class="column is-half">
                            <label class="label">Kolejka</label>
                            <div class="control">
                                <div class="select">
                                    {{ form.queue }}
                                </div>
                            </div>
                            {% if form.queue.errors %}
                                <p class="help custom-error">{{ form.queue.errors }}</p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="columns is-multiline is-mobile">
                        <div class="column is-half">
                            <label class="label">Gospodarz</label>
                            <div class="control">
                                <div class="select">
                                    {{ form.host_team }}
                                </div>
                            </div>
                            {% if form.host_team.errors %}
                                <p class="help custom-error">{{ form.host_team.errors }}</p>
                            {% endif %}
                        </div>
                        <div class="column is-half">
                            <label class="label">Goście</label>
                            <div class="control">
                                <div class="select">
                                    {{ form.guest_team }}
                                </div>
                            </div>
                            {% if form.guest_team.errors %}
                                <p class="help custom-error">{{ form.guest_team.errors }}</p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control has-text-centered">
                            <button class="button is-primary" type="submit">Zapisz</button>
                            <a class="button is-light" href="{% url 'Matches' %}">Anuluj</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .custom-error {
        font-size: 14px;
    }
    .error {
        color: red;
        font-size: 14px;
    }
</style>

{% endblock %}

FootballManager/templates/FootballManager/matches/info_match.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="columns is-centered">
        <div class="column is-half">
            <h1 class="title has-text-centered">Informacje o meczu</h1>
            <div class="box">
                {% csrf_token %}
                <div class="columns is-multiline is-mobile">
                    <div class="column is-half">
                        <label class="label">Data meczu</label>
                        <div class="field">
                            {{ match.date|date:"d.m.Y H:i" }}
                        </div>
                    </div>
                    <div class="column is-half">
                        <label class="label">Kolejka</label>
                        <div class="field">
                            {{ match.queue }}
                        </div>
                    </div>
                </div>
                <div class="columns is-multiline is-mobile">
                    <div class="column is-half">
                        <label class="label">Gospodarze</label>
                        <div class="field">
                            {{ match.host_team }}
                        </div>
                    </div>

                    <div class="column is-half">
                        <label class="label">Goście</label>
                        <div class="field">
                            {{ match.guest_team }}
                        </div>
                    </div>

                </div>

                <div class="field">
                    <div class="control has-text-centered">
                        <a class="button is-light" href="{% url 'Matches' %}">Wróć</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

FootballManager/templates/FootballManager/matches/matches.html
{% extends 'base.html' %}

{% block content %}
<div class="container has-text-centered">
    <table class="table is-fullwidth sortable">
        <thead>
            <tr>
                <th>Lp.</th>
                <th class="sortable-header">
                    Data <i class="fas fa-sort"></i>
                </th>
                <th class="sortable-header">
                    Kolejka <i class="fas fa-sort"></i>
                </th>
                <th>Gospodarz</th>
                <th>Gość</th>
                <th>Wynik</th>
                <th>Wydarzenia</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            {% for match in matches %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ match.date|date:"d.m.Y H:i" }}</td>
                <td>{{ match.queue.number }}</td>
                <td>{{ match.host_team }}</td>
                <td>{{ match.guest_team }}</td>
                <td>
                    {% if match.host_goals is not null and match.guest_goals is not null %}
                    {{ match.host_goals }} : {{ match.guest_goals }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                <td>
                    <ul>
                        {% for event in match.events.all %}
                        <li>{{ event.get_event_type_display }} - {{ event.minute }}' ({{ event.footballer }})</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a href="{% url 'Info match' match.id %}" class="button is-small is-info">
                        <span class="icon">
                            <i class="fas fa-info"></i>
                        </span>
                        <span>info</span>
                    </a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'Edit match' match.id %}" class="button is-small">
                        <span class="icon">
                            <i class="fas fa-edit"></i>
                        </span>
                        <span>Edytuj</span>
                    </a>
                    {% if match.date <= now %}
                    <a href="{% url 'Add match result' match.id %}" class="button is-small is-warning">
                        <span class="icon">
                            <i class="fas fa-poll-h"></i>
                        </span>
                        <span>Dodaj wynik</span>
                    </a>
                    {% else %}
                    <a href="#" class="button is-small is-warning" title="Dodanie wyniku dostępne po rozpoczęciu meczu" disabled>
                        <span class="icon">
                            <i class="fas fa-poll-h"></i>
                        </span>
                        <span>Dodaj wynik</span>
                    </a>
                    {% endif %}
                    <a href="{% url 'Delete match' match.id %}" class="button is-small is-danger">
                        <span class="icon">
                            <i class="fas fa-trash"></i>
                        </span>
                        <span>Usuń</span>
                    </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if user.is_authenticated %}
    <a href="/matches/add" class="button is-rounded">Dodaj mecz</a>
    {% endif %}
</div>
<!-- Include sorttable.js for sortable tables -->
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
<style>
    .sortable-header {
        cursor: pointer;
        user-select: none;
    }

    .sortable-header:hover {
        cursor: pointer;
        color: #3273dc;
        /* Primary color for better visibility */
    }

    .sortable-header .fa-sort {
        margin-left: 5px;
    }
</style>
{% endblock %}